FROM node:16-slim

ARG NEXT_PUBLIC_DOCSEARCH_APP_ID
ENV NEXT_PUBLIC_DOCSEARCH_APP_ID $NEXT_PUBLIC_DOCSEARCH_APP_ID

ARG NEXT_PUBLIC_DOCSEARCH_API_KEY
ENV NEXT_PUBLIC_DOCSEARCH_API_KEY $NEXT_PUBLIC_DOCSEARCH_API_KEY

ARG NEXT_PUBLIC_DOCSEARCH_INDEX_NAME
ENV NEXT_PUBLIC_DOCSEARCH_INDEX_NAME $NEXT_PUBLIC_DOCSEARCH_INDEX_NAME

RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y chromium


WORKDIR /app

COPY . /app


RUN npm i
RUN npm run build

EXPOSE 8080

ENV CHROME_BIN=/usr/bin/chromium-browser
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_ARGS='--no-sandbox'

ENTRYPOINT ["npm", "run", "start"]
